description: Run schedule


inputs:
  token:
    description: Personal Access Token
    required: false
    default: ''


runs:
  using: composite

  steps:
    - uses: li1ht2ay-3es/gi1-ac2io3s@rebase-repo
      with:
        remote_repo: lab313ru/rnc_propack_source
        remote_branch: master

        auto: true
        token: ${{ inputs.token }}


    - uses: li1ht2ay-3es/gi1-ac2io3s@keep-alive
      with:
        auto: true
        token: ${{ inputs.token }}


    - uses: li1ht2ay-3es/gi1-ac2io3s@keep-alive
      with:
        branch: build-windows

        auto: true
        token: ${{ inputs.token }}
