on:
  workflow_dispatch:
  schedule:
    - cron: '*/45 */23 */6 * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/rn1-pr2pa3k@cron
        with:
          token: ${{ secrets.token }}
